kind: Service
apiVersion: v1
metadata:
  name: kafka
spec:
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: NodePort
  selector:
    component: kafka
