kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      volumes:
       - name: test-volume
         hostPath:
           path: /home/ubuntu/spark
      containers:
        - name: spark-worker
          image: vpperego/spark-standalone:2.3.3
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          args: ["unset SPARK_WORKER_PORT;chmod +x spark-worker;./spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "3900m"
              memory: 7G
          volumeMounts:
            - mountPath: /data
              name: test-volume
