kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      volumes:
       - name: test-volume
         hostPath:
           path: /home/ubuntu/spark
      nodeSelector:
        sparkrole: master
      containers:
        - name: spark-master
          image: vpperego/spark-standalone:2.3.3
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          #  args: ["chmod +x common.sh;chmod +x spark-master;./spark-master"]
          args: ["unset SPARK_MASTER_PORT;$SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master"]
          #args: ["cat spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
            - containerPort: 6066
              #          resources:
              #requests:
              #cpu: "3"
              #memory: 7G
          volumeMounts:
            - mountPath: /data
              name: test-volume
