kind: Service
apiVersion: v1
metadata:
  name: spark-worker
spec:
  ports:
    - name: webuiw
      protocol: TCP
      port: 8081
    - name: bmng
      protocol: TCP
      port: 55000
    - name: driver
      protocol: TCP
      port: 55001
    - name: shuffle
      protocol: TCP
      port: 7337
  type: NodePort
  selector:
    component: spark-worker
