apiVersion: batch/v1
kind: Job
metadata:
  name: spark-q3-materialized
spec:
  completions: 3
  template:
    metadata:
      name: spark-q3-materialized
    spec:
      volumes:
       - name: test-volume
         hostPath:
           path: /home/ubuntu/spark
      restartPolicy: Never
      containers:
      - name: spark-q3-materialized
        image: vpperego/spark-standalone:2.3.3
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["spark-submit --master local[*] --conf \"spark.streaming.kafka.maxRatePerPartition=500\" --driver-memory 6g /data/joinExperiments.jar M-TPCQ3 hdfs:/q3-throughput.conf"]
        resources:
          requests:
            cpu: "3900m"
            memory: 7G
        volumeMounts:
            - mountPath: /data
              name: test-volume
      nodeSelector:
        sparkrole: master
