apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nn-pv-1
    labels:
      type: namenode
  spec:
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - lkworker04
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: default
    hostPath:
      path: "/home/ubuntu/hdfs-data/name"

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: dn-pv-1
  spec:
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - lkworker04
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: default
    hostPath:
      path: "/home/ubuntu/hdfs-data/data/1"

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: dn-pv-2
  spec:
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - lkworker04
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    storageClassName: default
    hostPath:
      path: "/home/ubuntu/hdfs-data/data/2"

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: hdfs-name
  spec:
    selector:
      matchLabels:
        type: namenode
    accessModes:
    - ReadWriteOnce
    storageClassName: default
    resources:
      requests:
        storage: 1Gi

kind: List
metadata: {}
