apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer
spec:
  completions: 1
  template:
    metadata:
      name: scala-test
    spec:
      volumes:
       - name: test-volume
         hostPath:
           path: /home/ubuntu/workload
      restartPolicy: Never
      containers:
      - name: scala-test
        image: vpperego/scala:2.11.8
        imagePullPolicy: Always
        command: ["/bin/sh","-c"]
        args: ["scala  /data/kafkaTools-assembly-0.1.jar /data/s-producer.conf"]
        volumeMounts:
            - mountPath: /data
              name: test-volume
      nodeSelector:
        role: kafka
