kind: Service
apiVersion: v1
metadata:
  name: spark-q3-materialized
spec:
  ports:
    - name: webui
      protocol: TCP
      port: 8080
    - name: spark
      protocol: TCP
      port: 7077
  type: NodePort
  selector:
    component: spark-q3-materialized
