kind: Deployment
apiVersion: apps/v1
metadata:
  name: hdfs-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hdfs-namenode
  template:
    metadata:
      labels:
        component: hdfs-namenode
    spec:
      containers:
        - name: hdfs-namenode
          image: vpperego/k8s-hdfs:2.7.7
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          args: ["echo \"$(hostname -i)  hdfs-namenode\" >> /etc/hosts; mv dn-core-site.xml  ${HADOOP_CONF_DIR}/core-site.xml ;$HADOOP_HOME/bin/hadoop namenode -format; $HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR namenode"]
          #          args: ["echo \"10.97.101.99   hdfs-namenode\" >> /etc/hosts; mv dn-core-site.xml  ${HADOOP_CONF_DIR}/core-site.xml;cat ${HADOOP_CONF_DIR}/core-site.xml "]

          ports:
            - containerPort: 22
              name: nn-ssh
            - containerPort: 8020
              name: nn-rpc
            - containerPort: 50070
              name: nn-web
          resources:
            requests:
              cpu: 100m
