kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hdfs-datanode
spec:
  replicas: 2
  selector:
    matchLabels:
      component: hdfs-datanode
  serviceName: "hdfs-datanode"
  template:
    metadata:
      labels:
        component: hdfs-datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: vpperego/k8s-hdfs:2.7.7
          imagePullPolicy: Always
          command: ["/bin/sh","-c"]
          args: ["mv dn-core-site.xml ${HADOOP_CONF_DIR}/core-site.xml;HADOOP_HOME/bin/hadoop datanode -format; $HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR datanode"]
          ports:
            - containerPort: 22
            - containerPort: 9000
          resources:
            requests:
              cpu: 100m
