apiVersion: v1
kind: Pod
metadata:
  name: kafka-test
spec:
  containers:
  - name: scala-test
    image: vpperego/kafka:2.2.0
    imagePullPolicy: IfNotPresent
    restartPolicy: Never
    command: ["/bin/sh","-c"]
    args: ["kafka-topics.sh --create --bootstrap-server kafka-broker:9092 --replication-factor 1 --partitions 4 --topic customer; kafka-topics.sh --create --bootstrap-server kafka-broker:9092 --replication-factor 1 --partitions 4 --topic order;kafka-topics.sh --create --bootstrap-server kafka-broker:9092 --replication-factor 1 --partitions 4 --topic lineitem"]
