kind: Service
apiVersion: v1
metadata:
  name: zookeeper
spec:
  ports:
    - name: foo
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: bar
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: foobar
      protocol: TCP
      port: 3888
      targetPort: 3888
  type: NodePort
  selector:
    component: zookeeper
